project:
  type: website
  
  render:
    - "*.qmd"
    - "!Scripts/Archive/"
    - "!weca report template.qmd"

website:
  title: "Woodland Ecological Condition Assessment"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    search: true
    contents:
      - index.qmd
      - 002_delphi_r2_instructions.qmd
      - 001_project background.qmd
      - 01_general approach.qmd
      - 02_methods.qmd

      - section: "Expert opinion - Indicators, Value Functions and Weightings"
        contents:
          - Estimating value functions and weightings - Delphi Round 2 analysis.qmd
          - 05_ind_tree_age.qmd
          - 06_canopy_nativness.qmd
          - 07_vert_struct.qmd
          - 08_native_tree_spceis_richness.qmd
          - 09_invasives.qmd
          - 10_deadwood.qmd
          - 11_avts.qmd
          - 12_extent.qmd
          - 13_regen.qmd
          - 14_herbivore.qmd
          - 15_tree-heath.qmd
          - 16_ground-flora.qmd
          - 17_horizontal-complexity.qmd
          - 18_anthro-damage.qmd
          - 04_Importance weightings.qmd

      - Exploring Old Condition Data.qmd

number-depth: 0


format:
  html:
    toc: true
    toc-location: right
    toc-depth: 5
    toc-float: true       # Optional: makes the table of contents float on the page
    theme: sandstone # could go cosmo
    lightbox: true
    code-fold: true       # Enables folding
    code-summary: "Show code"  # Optional: custom label on the fold button
    fig-width: 6
    fig-asp: 0.618
    reference-location: margin
    anchor-sections: true
    embed-resources: FALSE

editor: visual

prefer-html: true

execute:
  echo: false
  warning: false

bibliography: references.bib

css: style.css

comments:
  hypothesis: 
    theme: clean