project:
  type: book

book:
  title: "Woodland Condition Assessment - Expert Opinion"
  author: "Ewan McHenry, Martin Hügi, Saul Herbert and Christen Reid"
  date: today
  date-format: "D MMM, YYYY"
  chapters:
    - index.qmd
    - 01_general approach.qmd
    - 02_methods.qmd
    - 03_participation and survey completion.qmd
    - 04_Importance weightings.qmd
    - 05_ind_tree_age.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 6
    fig-asp: 0.618
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  echo: false
  warning: false
