project:
  type: book

book:
  title: "Woodland Condition Assessment - Expert Opinion"
  author: "Ewan McHenry, Martin Hügi, Saul Herbert and Christine Reid"
  date: today
  search: true
  date-format: "D MMM, YYYY"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 002_delphi_r2_instructions.qmd
    - 001_project background.qmd
    - 01_general approach.qmd
    - 05_ind_tree_age.qmd
    - 06_canopy_nativness.qmd
    - 07_vert_struct.qmd
    - 08_native_tree_spceis_richness.qmd
    - 09_invasives.qmd
    - 10_deadwood.qmd
    - 11_avts.qmd
    - 12_extent.qmd
    - 13_regen.qmd
    - 14_herbivore.qmd
    - 15_tree-heath.qmd
    - 16_ground-flora.qmd
    - 17_horizontal-complexity.qmd
    - 18_anthro-damage.qmd
    - 04_Importance weightings.qmd
    - 02_methods.qmd
    - Exploring "Old" condition data.qmd
    
number-depth: 0

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 6
    fig-asp: 0.618
    reference-location: margin
    anchor-sections: true
    embed-resources: FALSE
    
  pdf:
    documentclass: scrreprt

editor: visual

prefer-html: true

execute:
  echo: false
  warning: false

css: style.css

comments:
  hypothesis: 
    theme: clean